apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: ps-namespace
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: ps-app
  template:
    metadata:
      labels:
        app: ps-app
    spec:
      volumes:
        - name: my-pvc-ref
          persistentVolumeClaim:
            claimName: my-app-pvc
      containers:
        - name: "ps-container"
          image: pratikshinde55/apache-webserver:v3
          volumeMounts:
            - name: my-pvc-ref
              mountPath: "/usr/local/apache2/htdocs/"
      nodeSelector:
        node-type: ps
      tolerations:
        - key: "dedicated"
          operator: "Equal"
          value: "ps"
          effect: "NoSchedule"

---

apiVersion: v1
kind: Service
metadata:
  name: my-app-svc
  namespace: ps-namespace
spec:
  type: NodePort
  selector:
    app: ps-app
  ports:
    - targetPort: 80
      port: 1234
      nodePort: 30055
